GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWsiLCJpYXQiOjE2OTc0OTMxMjV9.zB-u8-oOtX74rhLafUsGF3dBk3C4k5HPOikM14lTZOk

###
POST http://localhost:3000/login
Content-Type: application/json

{"username": "Ak"} 

// if i don't do it this specific way it does not work!